//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace E_Commerce_Site
{
    public partial class AdminUpdate
    {
        protected global::System.Web.UI.WebControls.TextBox TextBox1;
        protected global::System.Web.UI.WebControls.TextBox TextBox2;
        protected global::System.Web.UI.WebControls.TextBox TextBox3;
        protected global::System.Web.UI.WebControls.TextBox TextBox4;
        protected global::System.Web.UI.WebControls.TextBox TextBox5;
        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;

    }
}
