//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace E_Commerce_Site
{
    public partial class DeleteItem
    {
        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        public new E_Commerce_Site.index Master
        {
            get
            {
                return ((E_Commerce_Site.index)(base.Master));
            }
        }
    }
}
